source_list:
  - CP


OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data

SB:
  mysql_conf:
    partition_column: App_Transaction_Id
    query: "(select * from TRANSACTIONSYNC) as t"


s3_conf:
  s3_bucket: stagingmonksbala
  staging_location: staging




CP:
  mongodb_config:
    database: school
    collection: students

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT


