source_list:
  - SB
  - OL
  - CP
  - ADDR


OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data

SB:
  mysql_conf:
    partition_column: App_Transaction_Id
    query: "(select * from TRANSACTIONSYNC) as t"


s3_conf:
  s3_bucket: stagingmonksbala
  staging_location: staging




ADDR:
  mongodb_config:
    database: customer
    collection: address

CP:
  s3_conf_read:
    s3_bucket_read: test-spark-test

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT


